### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by ksdme** [frextrite/coala-jetbrains#4]
We need Travis or some other CI system setup. This should at least run `coala` and should also run the required tests.

**Comment by frextrite** [comment]
I'll take a look at this in the next week or the first week of the second phase.

**Comment by ksdme** [comment]
This needs to be done in this phase, basic infrastructure to test and lint check your code needs to exist. I am sorry I did not point this out soon enough.

**Comment by frextrite** [comment]
Okay, I'll try implementing this as well. 

What should be the complexity of the basic builds? Single OS (any Linux distro) + run tests + build plugin would work?

> lint check your code

Can you explain this?

**Comment by ksdme** [comment]
> What should be the complexity of the basic builds? Single OS (any Linux distro) + run tests + build plugin would work?

That should be enough for now.

> Can you explain this?

Run `coala` on CI.
